### PR TITLE
[DO NOT MERGE] Use the Mirage 3 APIs

### PR DESCRIPTION
**Pull request by djs55**
This PR should be merged when we want master to be Mirage 3 only, i.e. at around Mirage 3 release time.

### CODE REVIEW

**Comment by djs55** [comment]
Related to #33

**Comment by avsm** [comment]
This conflicts now; should we merge to master soon now that mirage3 beta is imminent?

**Comment by avsm** [comment]
closed in favour of #41

**Comment by djs55** [comment]
I think vpnkit hasn't been updated to Mirage 3 yet-- it would be good to
keep this in sync with that.

**Pull request closed without merging**
